# Generated by Django 5.1.6 on 2025-03-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='No_of_doctors',
            new_name='no_of_doctors',
        ),
    ]
